// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data;

namespace WebApplication2.Migrations
{
    [DbContext(typeof(ShopDatabaseContext))]
    [Migration("20200504100144_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication2.Models.Address", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("customer");

                    b.Property<string>("detail");

                    b.Property<bool>("isDefaultAddress");

                    b.Property<bool>("isHomeAddress");

                    b.Property<string>("phone");

                    b.HasKey("id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("WebApplication2.Models.Admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address");

                    b.Property<DateTime>("birth");

                    b.Property<DateTime>("closed");

                    b.Property<DateTime>("created");

                    b.Property<string>("email");

                    b.Property<string>("fullName");

                    b.Property<bool>("gender");

                    b.Property<string>("password");

                    b.Property<string>("role");

                    b.Property<string>("type");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("WebApplication2.Models.Comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("account");

                    b.Property<string>("content");

                    b.Property<DateTime>("created");

                    b.Property<int>("product");

                    b.Property<int>("stars");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("WebApplication2.Models.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("birth");

                    b.Property<DateTime>("closed");

                    b.Property<DateTime>("created");

                    b.Property<string>("email");

                    b.Property<string>("fullName");

                    b.Property<bool>("gender");

                    b.Property<string>("password");

                    b.Property<string>("type");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("WebApplication2.Models.Image", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("content");

                    b.Property<DateTime>("created");

                    b.Property<string>("format");

                    b.Property<int>("whose");

                    b.HasKey("id");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("WebApplication2.Models.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cart");

                    b.Property<int>("order");

                    b.Property<int>("price");

                    b.Property<int>("product");

                    b.Property<int>("quantity");

                    b.HasKey("id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("WebApplication2.Models.News", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("admin");

                    b.Property<string>("content");

                    b.Property<DateTime>("created");

                    b.Property<string>("type");

                    b.HasKey("id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("WebApplication2.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address");

                    b.Property<int>("customer");

                    b.Property<DateTime>("ordered");

                    b.Property<int>("promotion");

                    b.Property<string>("status");

                    b.Property<int>("total");

                    b.HasKey("id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("WebApplication2.Models.Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("method");

                    b.Property<string>("note");

                    b.Property<int>("order");

                    b.Property<DateTime>("paid");

                    b.Property<int>("payer");

                    b.HasKey("id");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("WebApplication2.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("category");

                    b.Property<string>("description");

                    b.Property<string>("name");

                    b.Property<string>("price");

                    b.Property<string>("summary");

                    b.Property<string>("supplier");

                    b.HasKey("id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("WebApplication2.Models.ProductSize", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("product");

                    b.Property<string>("quantity");

                    b.Property<string>("size");

                    b.HasKey("id");

                    b.ToTable("ProductSize");
                });

            modelBuilder.Entity("WebApplication2.Models.Promotion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("admin");

                    b.Property<string>("by");

                    b.Property<DateTime>("created");

                    b.Property<string>("description");

                    b.Property<float>("discount");

                    b.Property<DateTime>("due");

                    b.HasKey("id");

                    b.ToTable("Promotion");
                });

            modelBuilder.Entity("WebApplication2.Models.ShoppingCart", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created");

                    b.Property<int>("customer");

                    b.Property<DateTime>("discard");

                    b.HasKey("id");

                    b.ToTable("ShoppingCart");
                });
#pragma warning restore 612, 618
        }
    }
}
